# Generated by Django 5.2.5 on 2025-11-13 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_bio_customuser_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='number',
            field=models.TextField(blank=True, max_length=15),
        ),
    ]
