# Generated by Django 5.2.5 on 2025-08-27 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_category_description_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='included_in',
            field=models.ManyToManyField(related_name='participants', to='events.participant'),
        ),
    ]
