# Generated by Django 5.2.5 on 2025-09-22 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='asset',
            field=models.ImageField(blank=True, default='asset/default_img.jpg', null=True, upload_to='asset'),
        ),
    ]
